### ISSUE TITLE
I couldn't load the plugin

### ISSUE THREAD

**Issue by MyNameIsMinhReal** [TomasGnG/DynamicSeasons#3]
[ERROR] Error occurred while enabling DynamicSeasons v1.9.3 (Is it up to date?)

java.lang.NoClassDefFoundError: net/kyori/adventure/key/Key

at de.tomasgng.DynamicSeasons.onEnable(DynamicSeasons.java:38) ~[?:?]

at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]

at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]

at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:589) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]

at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:414) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]

at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]

at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:973) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]

at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]

at java.lang.Thread.run(Thread.java:1589) ~[?:?]

Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.key.Key

at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]

... 12 more

**Comment by TomasGnG** [comment]
Hey, currently the plugin doesn't work with Spigot because I am using methods from paper and that's why you're getting this error.
To fix this error you can do 2 things:
1. Upgrade your server to paper.
2. Wait for the Spigot version (I will work on that soon)
3.

Next time you can come to my discord :)
